apiVersion: v1
kind: Service
metadata:
  name: example-service2
  labels:
    app: example-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31803
    protocol: TCP
    name: tcp
  selector:
    app: example-service2