apiVersion: v1
kind: Service
metadata:
  name: example-service1
  labels:
    app: example-service1
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31802
    protocol: TCP
    name: tcp
  selector:
    app: example-service1